### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by naydden** [xuanxu/spaceup_bcn#13]
Creo que,a nivel de imagen, estaría bien añadirle el certificado. 

¿Se podría hacer?

**Comment by Juanlu001** [comment]
Documentación relevante: https://www.netlify.com/docs/ssl/

**Comment by Juanlu001** [comment]
El certificado HTTPS estaba activado, pero ahora he activado el HTTPS obligatorio 😉 ¡Cerrando!
